// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package type_builder

import baml "github.com/boundaryml/baml/engine/language_client_go/pkg"

type AcceptanceCriterionClassView struct {
	inner baml.ClassBuilder
}

func (t *AcceptanceCriterionClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *AcceptanceCriterionClassView) PropertyCriterion() (ClassPropertyView, error) {
	return t.inner.Property("criterion")
}

func (t *AcceptanceCriterionClassView) PropertyTestable() (ClassPropertyView, error) {
	return t.inner.Property("testable")
}

func (t *AcceptanceCriterionClassView) PropertyVerification_method() (ClassPropertyView, error) {
	return t.inner.Property("verification_method")
}

func (t *TypeBuilder) AcceptanceCriterion() (*AcceptanceCriterionClassView, error) {
	bld, err := t.inner.Class("AcceptanceCriterion")
	if err != nil {
		return nil, err
	}
	return &AcceptanceCriterionClassView{inner: bld}, nil
}

func (t *AcceptanceCriterionClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type AlternativeClassView struct {
	inner baml.ClassBuilder
}

func (t *AlternativeClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *AlternativeClassView) PropertyApproach() (ClassPropertyView, error) {
	return t.inner.Property("approach")
}

func (t *AlternativeClassView) PropertyPros() (ClassPropertyView, error) {
	return t.inner.Property("pros")
}

func (t *AlternativeClassView) PropertyCons() (ClassPropertyView, error) {
	return t.inner.Property("cons")
}

func (t *AlternativeClassView) PropertyWhy_rejected() (ClassPropertyView, error) {
	return t.inner.Property("why_rejected")
}

func (t *TypeBuilder) Alternative() (*AlternativeClassView, error) {
	bld, err := t.inner.Class("Alternative")
	if err != nil {
		return nil, err
	}
	return &AlternativeClassView{inner: bld}, nil
}

func (t *AlternativeClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type BehaviorChangeClassView struct {
	inner baml.ClassBuilder
}

func (t *BehaviorChangeClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *BehaviorChangeClassView) PropertyComponent() (ClassPropertyView, error) {
	return t.inner.Property("component")
}

func (t *BehaviorChangeClassView) PropertyCurrent_behavior() (ClassPropertyView, error) {
	return t.inner.Property("current_behavior")
}

func (t *BehaviorChangeClassView) PropertyDesired_behavior() (ClassPropertyView, error) {
	return t.inner.Property("desired_behavior")
}

func (t *BehaviorChangeClassView) PropertyChange_type() (ClassPropertyView, error) {
	return t.inner.Property("change_type")
}

func (t *TypeBuilder) BehaviorChange() (*BehaviorChangeClassView, error) {
	bld, err := t.inner.Class("BehaviorChange")
	if err != nil {
		return nil, err
	}
	return &BehaviorChangeClassView{inner: bld}, nil
}

func (t *BehaviorChangeClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type CodeConstraintsClassView struct {
	inner baml.ClassBuilder
}

func (t *CodeConstraintsClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *CodeConstraintsClassView) PropertyMax_file_size_lines() (ClassPropertyView, error) {
	return t.inner.Property("max_file_size_lines")
}

func (t *CodeConstraintsClassView) PropertyPreserve_formatting() (ClassPropertyView, error) {
	return t.inner.Property("preserve_formatting")
}

func (t *CodeConstraintsClassView) PropertyMaintain_compatibility() (ClassPropertyView, error) {
	return t.inner.Property("maintain_compatibility")
}

func (t *CodeConstraintsClassView) PropertyAllowed_imports() (ClassPropertyView, error) {
	return t.inner.Property("allowed_imports")
}

func (t *CodeConstraintsClassView) PropertyForbidden_patterns() (ClassPropertyView, error) {
	return t.inner.Property("forbidden_patterns")
}

func (t *TypeBuilder) CodeConstraints() (*CodeConstraintsClassView, error) {
	bld, err := t.inner.Class("CodeConstraints")
	if err != nil {
		return nil, err
	}
	return &CodeConstraintsClassView{inner: bld}, nil
}

func (t *CodeConstraintsClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type CodeContextClassView struct {
	inner baml.ClassBuilder
}

func (t *CodeContextClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *CodeContextClassView) PropertyFile_contents() (ClassPropertyView, error) {
	return t.inner.Property("file_contents")
}

func (t *CodeContextClassView) PropertyProject_structure() (ClassPropertyView, error) {
	return t.inner.Property("project_structure")
}

func (t *CodeContextClassView) PropertyLanguage() (ClassPropertyView, error) {
	return t.inner.Property("language")
}

func (t *CodeContextClassView) PropertyFramework() (ClassPropertyView, error) {
	return t.inner.Property("framework")
}

func (t *CodeContextClassView) PropertyStyle_guide() (ClassPropertyView, error) {
	return t.inner.Property("style_guide")
}

func (t *TypeBuilder) CodeContext() (*CodeContextClassView, error) {
	bld, err := t.inner.Class("CodeContext")
	if err != nil {
		return nil, err
	}
	return &CodeContextClassView{inner: bld}, nil
}

func (t *CodeContextClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type CodeGenerationRequestClassView struct {
	inner baml.ClassBuilder
}

func (t *CodeGenerationRequestClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *CodeGenerationRequestClassView) PropertyStep() (ClassPropertyView, error) {
	return t.inner.Property("step")
}

func (t *CodeGenerationRequestClassView) PropertyContext() (ClassPropertyView, error) {
	return t.inner.Property("context")
}

func (t *CodeGenerationRequestClassView) PropertyConstraints() (ClassPropertyView, error) {
	return t.inner.Property("constraints")
}

func (t *TypeBuilder) CodeGenerationRequest() (*CodeGenerationRequestClassView, error) {
	bld, err := t.inner.Class("CodeGenerationRequest")
	if err != nil {
		return nil, err
	}
	return &CodeGenerationRequestClassView{inner: bld}, nil
}

func (t *CodeGenerationRequestClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type CodeGenerationResultClassView struct {
	inner baml.ClassBuilder
}

func (t *CodeGenerationResultClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *CodeGenerationResultClassView) PropertyFile_changes() (ClassPropertyView, error) {
	return t.inner.Property("file_changes")
}

func (t *CodeGenerationResultClassView) PropertyCommit_message() (ClassPropertyView, error) {
	return t.inner.Property("commit_message")
}

func (t *CodeGenerationResultClassView) PropertyNotes() (ClassPropertyView, error) {
	return t.inner.Property("notes")
}

func (t *TypeBuilder) CodeGenerationResult() (*CodeGenerationResultClassView, error) {
	bld, err := t.inner.Class("CodeGenerationResult")
	if err != nil {
		return nil, err
	}
	return &CodeGenerationResultClassView{inner: bld}, nil
}

func (t *CodeGenerationResultClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type CodeQualityMetricsClassView struct {
	inner baml.ClassBuilder
}

func (t *CodeQualityMetricsClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *CodeQualityMetricsClassView) PropertyCyclomatic_complexity() (ClassPropertyView, error) {
	return t.inner.Property("cyclomatic_complexity")
}

func (t *CodeQualityMetricsClassView) PropertyCognitive_complexity() (ClassPropertyView, error) {
	return t.inner.Property("cognitive_complexity")
}

func (t *CodeQualityMetricsClassView) PropertyLines_of_code() (ClassPropertyView, error) {
	return t.inner.Property("lines_of_code")
}

func (t *CodeQualityMetricsClassView) PropertyLines_of_comments() (ClassPropertyView, error) {
	return t.inner.Property("lines_of_comments")
}

func (t *CodeQualityMetricsClassView) PropertyComment_ratio() (ClassPropertyView, error) {
	return t.inner.Property("comment_ratio")
}

func (t *CodeQualityMetricsClassView) PropertyDuplication_percent() (ClassPropertyView, error) {
	return t.inner.Property("duplication_percent")
}

func (t *TypeBuilder) CodeQualityMetrics() (*CodeQualityMetricsClassView, error) {
	bld, err := t.inner.Class("CodeQualityMetrics")
	if err != nil {
		return nil, err
	}
	return &CodeQualityMetricsClassView{inner: bld}, nil
}

func (t *CodeQualityMetricsClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type CommitMessageClassView struct {
	inner baml.ClassBuilder
}

func (t *CommitMessageClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *CommitMessageClassView) PropertySubject() (ClassPropertyView, error) {
	return t.inner.Property("subject")
}

func (t *CommitMessageClassView) PropertyBody() (ClassPropertyView, error) {
	return t.inner.Property("body")
}

func (t *CommitMessageClassView) PropertyType() (ClassPropertyView, error) {
	return t.inner.Property("type")
}

func (t *TypeBuilder) CommitMessage() (*CommitMessageClassView, error) {
	bld, err := t.inner.Class("CommitMessage")
	if err != nil {
		return nil, err
	}
	return &CommitMessageClassView{inner: bld}, nil
}

func (t *CommitMessageClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type CommitMessageRequestClassView struct {
	inner baml.ClassBuilder
}

func (t *CommitMessageRequestClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *CommitMessageRequestClassView) PropertyFile_changes() (ClassPropertyView, error) {
	return t.inner.Property("file_changes")
}

func (t *CommitMessageRequestClassView) PropertyFeature_context() (ClassPropertyView, error) {
	return t.inner.Property("feature_context")
}

func (t *CommitMessageRequestClassView) PropertyStep_description() (ClassPropertyView, error) {
	return t.inner.Property("step_description")
}

func (t *TypeBuilder) CommitMessageRequest() (*CommitMessageRequestClassView, error) {
	bld, err := t.inner.Class("CommitMessageRequest")
	if err != nil {
		return nil, err
	}
	return &CommitMessageRequestClassView{inner: bld}, nil
}

func (t *CommitMessageRequestClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type ComplexityAssessmentClassView struct {
	inner baml.ClassBuilder
}

func (t *ComplexityAssessmentClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *ComplexityAssessmentClassView) PropertyLevel() (ClassPropertyView, error) {
	return t.inner.Property("level")
}

func (t *ComplexityAssessmentClassView) PropertyEstimated_steps() (ClassPropertyView, error) {
	return t.inner.Property("estimated_steps")
}

func (t *ComplexityAssessmentClassView) PropertyEstimated_files() (ClassPropertyView, error) {
	return t.inner.Property("estimated_files")
}

func (t *ComplexityAssessmentClassView) PropertyRationale() (ClassPropertyView, error) {
	return t.inner.Property("rationale")
}

func (t *TypeBuilder) ComplexityAssessment() (*ComplexityAssessmentClassView, error) {
	bld, err := t.inner.Class("ComplexityAssessment")
	if err != nil {
		return nil, err
	}
	return &ComplexityAssessmentClassView{inner: bld}, nil
}

func (t *ComplexityAssessmentClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type ComponentReferenceClassView struct {
	inner baml.ClassBuilder
}

func (t *ComponentReferenceClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *ComponentReferenceClassView) PropertyName() (ClassPropertyView, error) {
	return t.inner.Property("name")
}

func (t *ComponentReferenceClassView) PropertyPath() (ClassPropertyView, error) {
	return t.inner.Property("path")
}

func (t *ComponentReferenceClassView) PropertyType() (ClassPropertyView, error) {
	return t.inner.Property("type")
}

func (t *ComponentReferenceClassView) PropertyPurpose() (ClassPropertyView, error) {
	return t.inner.Property("purpose")
}

func (t *TypeBuilder) ComponentReference() (*ComponentReferenceClassView, error) {
	bld, err := t.inner.Class("ComponentReference")
	if err != nil {
		return nil, err
	}
	return &ComponentReferenceClassView{inner: bld}, nil
}

func (t *ComponentReferenceClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type CoverageGapClassView struct {
	inner baml.ClassBuilder
}

func (t *CoverageGapClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *CoverageGapClassView) PropertyFile_path() (ClassPropertyView, error) {
	return t.inner.Property("file_path")
}

func (t *CoverageGapClassView) PropertySymbol() (ClassPropertyView, error) {
	return t.inner.Property("symbol")
}

func (t *CoverageGapClassView) PropertyReason() (ClassPropertyView, error) {
	return t.inner.Property("reason")
}

func (t *TypeBuilder) CoverageGap() (*CoverageGapClassView, error) {
	bld, err := t.inner.Class("CoverageGap")
	if err != nil {
		return nil, err
	}
	return &CoverageGapClassView{inner: bld}, nil
}

func (t *CoverageGapClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type DependencyEdgeClassView struct {
	inner baml.ClassBuilder
}

func (t *DependencyEdgeClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *DependencyEdgeClassView) PropertyFrom_id() (ClassPropertyView, error) {
	return t.inner.Property("from_id")
}

func (t *DependencyEdgeClassView) PropertyTo_id() (ClassPropertyView, error) {
	return t.inner.Property("to_id")
}

func (t *DependencyEdgeClassView) PropertyEdge_type() (ClassPropertyView, error) {
	return t.inner.Property("edge_type")
}

func (t *TypeBuilder) DependencyEdge() (*DependencyEdgeClassView, error) {
	bld, err := t.inner.Class("DependencyEdge")
	if err != nil {
		return nil, err
	}
	return &DependencyEdgeClassView{inner: bld}, nil
}

func (t *DependencyEdgeClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type DependencyGraphClassView struct {
	inner baml.ClassBuilder
}

func (t *DependencyGraphClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *DependencyGraphClassView) PropertyNodes() (ClassPropertyView, error) {
	return t.inner.Property("nodes")
}

func (t *DependencyGraphClassView) PropertyEdges() (ClassPropertyView, error) {
	return t.inner.Property("edges")
}

func (t *TypeBuilder) DependencyGraph() (*DependencyGraphClassView, error) {
	bld, err := t.inner.Class("DependencyGraph")
	if err != nil {
		return nil, err
	}
	return &DependencyGraphClassView{inner: bld}, nil
}

func (t *DependencyGraphClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type DependencyNodeClassView struct {
	inner baml.ClassBuilder
}

func (t *DependencyNodeClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *DependencyNodeClassView) PropertyId() (ClassPropertyView, error) {
	return t.inner.Property("id")
}

func (t *DependencyNodeClassView) PropertyPath() (ClassPropertyView, error) {
	return t.inner.Property("path")
}

func (t *DependencyNodeClassView) PropertySymbol() (ClassPropertyView, error) {
	return t.inner.Property("symbol")
}

func (t *DependencyNodeClassView) PropertyNode_type() (ClassPropertyView, error) {
	return t.inner.Property("node_type")
}

func (t *TypeBuilder) DependencyNode() (*DependencyNodeClassView, error) {
	bld, err := t.inner.Class("DependencyNode")
	if err != nil {
		return nil, err
	}
	return &DependencyNodeClassView{inner: bld}, nil
}

func (t *DependencyNodeClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type FeatureSpecificationClassView struct {
	inner baml.ClassBuilder
}

func (t *FeatureSpecificationClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *FeatureSpecificationClassView) PropertyTitle() (ClassPropertyView, error) {
	return t.inner.Property("title")
}

func (t *FeatureSpecificationClassView) PropertyDescription() (ClassPropertyView, error) {
	return t.inner.Property("description")
}

func (t *FeatureSpecificationClassView) PropertyAcceptance_criteria() (ClassPropertyView, error) {
	return t.inner.Property("acceptance_criteria")
}

func (t *FeatureSpecificationClassView) PropertyPath_hints() (ClassPropertyView, error) {
	return t.inner.Property("path_hints")
}

func (t *FeatureSpecificationClassView) PropertyAdditional_context() (ClassPropertyView, error) {
	return t.inner.Property("additional_context")
}

func (t *FeatureSpecificationClassView) PropertyCategory() (ClassPropertyView, error) {
	return t.inner.Property("category")
}

func (t *TypeBuilder) FeatureSpecification() (*FeatureSpecificationClassView, error) {
	bld, err := t.inner.Class("FeatureSpecification")
	if err != nil {
		return nil, err
	}
	return &FeatureSpecificationClassView{inner: bld}, nil
}

func (t *FeatureSpecificationClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type FileChangeClassView struct {
	inner baml.ClassBuilder
}

func (t *FileChangeClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *FileChangeClassView) PropertyFile_path() (ClassPropertyView, error) {
	return t.inner.Property("file_path")
}

func (t *FileChangeClassView) PropertyAction() (ClassPropertyView, error) {
	return t.inner.Property("action")
}

func (t *FileChangeClassView) PropertyPrevious_path() (ClassPropertyView, error) {
	return t.inner.Property("previous_path")
}

func (t *FileChangeClassView) PropertyContent() (ClassPropertyView, error) {
	return t.inner.Property("content")
}

func (t *FileChangeClassView) PropertyPatch() (ClassPropertyView, error) {
	return t.inner.Property("patch")
}

func (t *FileChangeClassView) PropertyDescription() (ClassPropertyView, error) {
	return t.inner.Property("description")
}

func (t *TypeBuilder) FileChange() (*FileChangeClassView, error) {
	bld, err := t.inner.Class("FileChange")
	if err != nil {
		return nil, err
	}
	return &FileChangeClassView{inner: bld}, nil
}

func (t *FileChangeClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type FileImpactClassView struct {
	inner baml.ClassBuilder
}

func (t *FileImpactClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *FileImpactClassView) PropertyFile_path() (ClassPropertyView, error) {
	return t.inner.Property("file_path")
}

func (t *FileImpactClassView) PropertyImpact_type() (ClassPropertyView, error) {
	return t.inner.Property("impact_type")
}

func (t *FileImpactClassView) PropertyConfidence() (ClassPropertyView, error) {
	return t.inner.Property("confidence")
}

func (t *FileImpactClassView) PropertyRationale() (ClassPropertyView, error) {
	return t.inner.Property("rationale")
}

func (t *FileImpactClassView) PropertyAffected_symbols() (ClassPropertyView, error) {
	return t.inner.Property("affected_symbols")
}

func (t *TypeBuilder) FileImpact() (*FileImpactClassView, error) {
	bld, err := t.inner.Class("FileImpact")
	if err != nil {
		return nil, err
	}
	return &FileImpactClassView{inner: bld}, nil
}

func (t *FileImpactClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type FileToReviewClassView struct {
	inner baml.ClassBuilder
}

func (t *FileToReviewClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *FileToReviewClassView) PropertyPath() (ClassPropertyView, error) {
	return t.inner.Property("path")
}

func (t *FileToReviewClassView) PropertyContent() (ClassPropertyView, error) {
	return t.inner.Property("content")
}

func (t *FileToReviewClassView) PropertyDiff() (ClassPropertyView, error) {
	return t.inner.Property("diff")
}

func (t *TypeBuilder) FileToReview() (*FileToReviewClassView, error) {
	bld, err := t.inner.Class("FileToReview")
	if err != nil {
		return nil, err
	}
	return &FileToReviewClassView{inner: bld}, nil
}

func (t *FileToReviewClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type ImpactAnalysisResultClassView struct {
	inner baml.ClassBuilder
}

func (t *ImpactAnalysisResultClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *ImpactAnalysisResultClassView) PropertyDirect_impacts() (ClassPropertyView, error) {
	return t.inner.Property("direct_impacts")
}

func (t *ImpactAnalysisResultClassView) PropertyIndirect_impacts() (ClassPropertyView, error) {
	return t.inner.Property("indirect_impacts")
}

func (t *ImpactAnalysisResultClassView) PropertyDependency_graph() (ClassPropertyView, error) {
	return t.inner.Property("dependency_graph")
}

func (t *ImpactAnalysisResultClassView) PropertyTest_coverage() (ClassPropertyView, error) {
	return t.inner.Property("test_coverage")
}

func (t *TypeBuilder) ImpactAnalysisResult() (*ImpactAnalysisResultClassView, error) {
	bld, err := t.inner.Class("ImpactAnalysisResult")
	if err != nil {
		return nil, err
	}
	return &ImpactAnalysisResultClassView{inner: bld}, nil
}

func (t *ImpactAnalysisResultClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type ImplementationPlanClassView struct {
	inner baml.ClassBuilder
}

func (t *ImplementationPlanClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *ImplementationPlanClassView) PropertyPlan_id() (ClassPropertyView, error) {
	return t.inner.Property("plan_id")
}

func (t *ImplementationPlanClassView) PropertyTitle() (ClassPropertyView, error) {
	return t.inner.Property("title")
}

func (t *ImplementationPlanClassView) PropertySummary() (ClassPropertyView, error) {
	return t.inner.Property("summary")
}

func (t *ImplementationPlanClassView) PropertySteps() (ClassPropertyView, error) {
	return t.inner.Property("steps")
}

func (t *ImplementationPlanClassView) PropertyDependencies() (ClassPropertyView, error) {
	return t.inner.Property("dependencies")
}

func (t *ImplementationPlanClassView) PropertyEstimated_metrics() (ClassPropertyView, error) {
	return t.inner.Property("estimated_metrics")
}

func (t *ImplementationPlanClassView) PropertyAssumptions() (ClassPropertyView, error) {
	return t.inner.Property("assumptions")
}

func (t *ImplementationPlanClassView) PropertyAlternatives_considered() (ClassPropertyView, error) {
	return t.inner.Property("alternatives_considered")
}

func (t *TypeBuilder) ImplementationPlan() (*ImplementationPlanClassView, error) {
	bld, err := t.inner.Class("ImplementationPlan")
	if err != nil {
		return nil, err
	}
	return &ImplementationPlanClassView{inner: bld}, nil
}

func (t *ImplementationPlanClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type IterationContextClassView struct {
	inner baml.ClassBuilder
}

func (t *IterationContextClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *IterationContextClassView) PropertyBuild_output() (ClassPropertyView, error) {
	return t.inner.Property("build_output")
}

func (t *IterationContextClassView) PropertyTest_output() (ClassPropertyView, error) {
	return t.inner.Property("test_output")
}

func (t *IterationContextClassView) PropertyLint_output() (ClassPropertyView, error) {
	return t.inner.Property("lint_output")
}

func (t *IterationContextClassView) PropertyPrevious_attempts() (ClassPropertyView, error) {
	return t.inner.Property("previous_attempts")
}

func (t *TypeBuilder) IterationContext() (*IterationContextClassView, error) {
	bld, err := t.inner.Class("IterationContext")
	if err != nil {
		return nil, err
	}
	return &IterationContextClassView{inner: bld}, nil
}

func (t *IterationContextClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type IterationIssueClassView struct {
	inner baml.ClassBuilder
}

func (t *IterationIssueClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *IterationIssueClassView) PropertyType() (ClassPropertyView, error) {
	return t.inner.Property("type")
}

func (t *IterationIssueClassView) PropertyFile_path() (ClassPropertyView, error) {
	return t.inner.Property("file_path")
}

func (t *IterationIssueClassView) PropertyLine_number() (ClassPropertyView, error) {
	return t.inner.Property("line_number")
}

func (t *IterationIssueClassView) PropertyDescription() (ClassPropertyView, error) {
	return t.inner.Property("description")
}

func (t *IterationIssueClassView) PropertySeverity() (ClassPropertyView, error) {
	return t.inner.Property("severity")
}

func (t *TypeBuilder) IterationIssue() (*IterationIssueClassView, error) {
	bld, err := t.inner.Class("IterationIssue")
	if err != nil {
		return nil, err
	}
	return &IterationIssueClassView{inner: bld}, nil
}

func (t *IterationIssueClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type IterationPlanClassView struct {
	inner baml.ClassBuilder
}

func (t *IterationPlanClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *IterationPlanClassView) PropertyStrategy() (ClassPropertyView, error) {
	return t.inner.Property("strategy")
}

func (t *IterationPlanClassView) PropertySteps_to_retry() (ClassPropertyView, error) {
	return t.inner.Property("steps_to_retry")
}

func (t *IterationPlanClassView) PropertyFiles_to_fix() (ClassPropertyView, error) {
	return t.inner.Property("files_to_fix")
}

func (t *IterationPlanClassView) PropertyAdditional_context() (ClassPropertyView, error) {
	return t.inner.Property("additional_context")
}

func (t *TypeBuilder) IterationPlan() (*IterationPlanClassView, error) {
	bld, err := t.inner.Class("IterationPlan")
	if err != nil {
		return nil, err
	}
	return &IterationPlanClassView{inner: bld}, nil
}

func (t *IterationPlanClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type IterationRequestClassView struct {
	inner baml.ClassBuilder
}

func (t *IterationRequestClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *IterationRequestClassView) PropertyOriginal_plan() (ClassPropertyView, error) {
	return t.inner.Property("original_plan")
}

func (t *IterationRequestClassView) PropertyFailed_step() (ClassPropertyView, error) {
	return t.inner.Property("failed_step")
}

func (t *IterationRequestClassView) PropertyIssues() (ClassPropertyView, error) {
	return t.inner.Property("issues")
}

func (t *IterationRequestClassView) PropertyContext() (ClassPropertyView, error) {
	return t.inner.Property("context")
}

func (t *TypeBuilder) IterationRequest() (*IterationRequestClassView, error) {
	bld, err := t.inner.Class("IterationRequest")
	if err != nil {
		return nil, err
	}
	return &IterationRequestClassView{inner: bld}, nil
}

func (t *IterationRequestClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type NormalizedSpecificationClassView struct {
	inner baml.ClassBuilder
}

func (t *NormalizedSpecificationClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *NormalizedSpecificationClassView) PropertyProblem_statement() (ClassPropertyView, error) {
	return t.inner.Property("problem_statement")
}

func (t *NormalizedSpecificationClassView) PropertyBehavior_changes() (ClassPropertyView, error) {
	return t.inner.Property("behavior_changes")
}

func (t *NormalizedSpecificationClassView) PropertyComponents() (ClassPropertyView, error) {
	return t.inner.Property("components")
}

func (t *NormalizedSpecificationClassView) PropertyAcceptance_criteria() (ClassPropertyView, error) {
	return t.inner.Property("acceptance_criteria")
}

func (t *NormalizedSpecificationClassView) PropertyRisks() (ClassPropertyView, error) {
	return t.inner.Property("risks")
}

func (t *NormalizedSpecificationClassView) PropertyComplexity() (ClassPropertyView, error) {
	return t.inner.Property("complexity")
}

func (t *TypeBuilder) NormalizedSpecification() (*NormalizedSpecificationClassView, error) {
	bld, err := t.inner.Class("NormalizedSpecification")
	if err != nil {
		return nil, err
	}
	return &NormalizedSpecificationClassView{inner: bld}, nil
}

func (t *NormalizedSpecificationClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type PlanMetricsClassView struct {
	inner baml.ClassBuilder
}

func (t *PlanMetricsClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *PlanMetricsClassView) PropertyTotal_steps() (ClassPropertyView, error) {
	return t.inner.Property("total_steps")
}

func (t *PlanMetricsClassView) PropertyEstimated_tokens() (ClassPropertyView, error) {
	return t.inner.Property("estimated_tokens")
}

func (t *PlanMetricsClassView) PropertyEstimated_files_total() (ClassPropertyView, error) {
	return t.inner.Property("estimated_files_total")
}

func (t *PlanMetricsClassView) PropertyEstimated_new_files() (ClassPropertyView, error) {
	return t.inner.Property("estimated_new_files")
}

func (t *PlanMetricsClassView) PropertyEstimated_modified() (ClassPropertyView, error) {
	return t.inner.Property("estimated_modified")
}

func (t *PlanMetricsClassView) PropertyEstimated_deleted() (ClassPropertyView, error) {
	return t.inner.Property("estimated_deleted")
}

func (t *TypeBuilder) PlanMetrics() (*PlanMetricsClassView, error) {
	bld, err := t.inner.Class("PlanMetrics")
	if err != nil {
		return nil, err
	}
	return &PlanMetricsClassView{inner: bld}, nil
}

func (t *PlanMetricsClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type PlanStepClassView struct {
	inner baml.ClassBuilder
}

func (t *PlanStepClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *PlanStepClassView) PropertyStep_number() (ClassPropertyView, error) {
	return t.inner.Property("step_number")
}

func (t *PlanStepClassView) PropertyAction() (ClassPropertyView, error) {
	return t.inner.Property("action")
}

func (t *PlanStepClassView) PropertyRationale() (ClassPropertyView, error) {
	return t.inner.Property("rationale")
}

func (t *PlanStepClassView) PropertyTarget_files() (ClassPropertyView, error) {
	return t.inner.Property("target_files")
}

func (t *PlanStepClassView) PropertyPrerequisites() (ClassPropertyView, error) {
	return t.inner.Property("prerequisites")
}

func (t *PlanStepClassView) PropertyExpected_outcome() (ClassPropertyView, error) {
	return t.inner.Property("expected_outcome")
}

func (t *PlanStepClassView) PropertyVerification() (ClassPropertyView, error) {
	return t.inner.Property("verification")
}

func (t *PlanStepClassView) PropertyEstimated_tokens() (ClassPropertyView, error) {
	return t.inner.Property("estimated_tokens")
}

func (t *TypeBuilder) PlanStep() (*PlanStepClassView, error) {
	bld, err := t.inner.Class("PlanStep")
	if err != nil {
		return nil, err
	}
	return &PlanStepClassView{inner: bld}, nil
}

func (t *PlanStepClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type ReviewAssessmentClassView struct {
	inner baml.ClassBuilder
}

func (t *ReviewAssessmentClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *ReviewAssessmentClassView) PropertyOverall_score() (ClassPropertyView, error) {
	return t.inner.Property("overall_score")
}

func (t *ReviewAssessmentClassView) PropertyRecommendation() (ClassPropertyView, error) {
	return t.inner.Property("recommendation")
}

func (t *ReviewAssessmentClassView) PropertySummary() (ClassPropertyView, error) {
	return t.inner.Property("summary")
}

func (t *ReviewAssessmentClassView) PropertyIssues() (ClassPropertyView, error) {
	return t.inner.Property("issues")
}

func (t *ReviewAssessmentClassView) PropertySuggestions() (ClassPropertyView, error) {
	return t.inner.Property("suggestions")
}

func (t *ReviewAssessmentClassView) PropertyMetrics() (ClassPropertyView, error) {
	return t.inner.Property("metrics")
}

func (t *TypeBuilder) ReviewAssessment() (*ReviewAssessmentClassView, error) {
	bld, err := t.inner.Class("ReviewAssessment")
	if err != nil {
		return nil, err
	}
	return &ReviewAssessmentClassView{inner: bld}, nil
}

func (t *ReviewAssessmentClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type ReviewContextClassView struct {
	inner baml.ClassBuilder
}

func (t *ReviewContextClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *ReviewContextClassView) PropertyFeature_description() (ClassPropertyView, error) {
	return t.inner.Property("feature_description")
}

func (t *ReviewContextClassView) PropertyAcceptance_criteria() (ClassPropertyView, error) {
	return t.inner.Property("acceptance_criteria")
}

func (t *ReviewContextClassView) PropertyLanguage() (ClassPropertyView, error) {
	return t.inner.Property("language")
}

func (t *ReviewContextClassView) PropertyCoding_standards() (ClassPropertyView, error) {
	return t.inner.Property("coding_standards")
}

func (t *TypeBuilder) ReviewContext() (*ReviewContextClassView, error) {
	bld, err := t.inner.Class("ReviewContext")
	if err != nil {
		return nil, err
	}
	return &ReviewContextClassView{inner: bld}, nil
}

func (t *ReviewContextClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type ReviewIssueClassView struct {
	inner baml.ClassBuilder
}

func (t *ReviewIssueClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *ReviewIssueClassView) PropertyId() (ClassPropertyView, error) {
	return t.inner.Property("id")
}

func (t *ReviewIssueClassView) PropertyType() (ClassPropertyView, error) {
	return t.inner.Property("type")
}

func (t *ReviewIssueClassView) PropertySeverity() (ClassPropertyView, error) {
	return t.inner.Property("severity")
}

func (t *ReviewIssueClassView) PropertyFile_path() (ClassPropertyView, error) {
	return t.inner.Property("file_path")
}

func (t *ReviewIssueClassView) PropertyLine_start() (ClassPropertyView, error) {
	return t.inner.Property("line_start")
}

func (t *ReviewIssueClassView) PropertyLine_end() (ClassPropertyView, error) {
	return t.inner.Property("line_end")
}

func (t *ReviewIssueClassView) PropertyTitle() (ClassPropertyView, error) {
	return t.inner.Property("title")
}

func (t *ReviewIssueClassView) PropertyDescription() (ClassPropertyView, error) {
	return t.inner.Property("description")
}

func (t *ReviewIssueClassView) PropertySuggestion() (ClassPropertyView, error) {
	return t.inner.Property("suggestion")
}

func (t *ReviewIssueClassView) PropertyCode_snippet() (ClassPropertyView, error) {
	return t.inner.Property("code_snippet")
}

func (t *TypeBuilder) ReviewIssue() (*ReviewIssueClassView, error) {
	bld, err := t.inner.Class("ReviewIssue")
	if err != nil {
		return nil, err
	}
	return &ReviewIssueClassView{inner: bld}, nil
}

func (t *ReviewIssueClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type ReviewRequestClassView struct {
	inner baml.ClassBuilder
}

func (t *ReviewRequestClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *ReviewRequestClassView) PropertyFiles_to_review() (ClassPropertyView, error) {
	return t.inner.Property("files_to_review")
}

func (t *ReviewRequestClassView) PropertyContext() (ClassPropertyView, error) {
	return t.inner.Property("context")
}

func (t *TypeBuilder) ReviewRequest() (*ReviewRequestClassView, error) {
	bld, err := t.inner.Class("ReviewRequest")
	if err != nil {
		return nil, err
	}
	return &ReviewRequestClassView{inner: bld}, nil
}

func (t *ReviewRequestClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type ReviewSuggestionClassView struct {
	inner baml.ClassBuilder
}

func (t *ReviewSuggestionClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *ReviewSuggestionClassView) PropertyTitle() (ClassPropertyView, error) {
	return t.inner.Property("title")
}

func (t *ReviewSuggestionClassView) PropertyDescription() (ClassPropertyView, error) {
	return t.inner.Property("description")
}

func (t *ReviewSuggestionClassView) PropertyFile_path() (ClassPropertyView, error) {
	return t.inner.Property("file_path")
}

func (t *ReviewSuggestionClassView) PropertyLine_number() (ClassPropertyView, error) {
	return t.inner.Property("line_number")
}

func (t *ReviewSuggestionClassView) PropertyPriority() (ClassPropertyView, error) {
	return t.inner.Property("priority")
}

func (t *TypeBuilder) ReviewSuggestion() (*ReviewSuggestionClassView, error) {
	bld, err := t.inner.Class("ReviewSuggestion")
	if err != nil {
		return nil, err
	}
	return &ReviewSuggestionClassView{inner: bld}, nil
}

func (t *ReviewSuggestionClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type RiskClassView struct {
	inner baml.ClassBuilder
}

func (t *RiskClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *RiskClassView) PropertyDescription() (ClassPropertyView, error) {
	return t.inner.Property("description")
}

func (t *RiskClassView) PropertyLevel() (ClassPropertyView, error) {
	return t.inner.Property("level")
}

func (t *RiskClassView) PropertyMitigation() (ClassPropertyView, error) {
	return t.inner.Property("mitigation")
}

func (t *TypeBuilder) Risk() (*RiskClassView, error) {
	bld, err := t.inner.Class("Risk")
	if err != nil {
		return nil, err
	}
	return &RiskClassView{inner: bld}, nil
}

func (t *RiskClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type StepDependencyClassView struct {
	inner baml.ClassBuilder
}

func (t *StepDependencyClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *StepDependencyClassView) PropertyFrom_step() (ClassPropertyView, error) {
	return t.inner.Property("from_step")
}

func (t *StepDependencyClassView) PropertyTo_step() (ClassPropertyView, error) {
	return t.inner.Property("to_step")
}

func (t *StepDependencyClassView) PropertyDependency_type() (ClassPropertyView, error) {
	return t.inner.Property("dependency_type")
}

func (t *StepDependencyClassView) PropertyReason() (ClassPropertyView, error) {
	return t.inner.Property("reason")
}

func (t *TypeBuilder) StepDependency() (*StepDependencyClassView, error) {
	bld, err := t.inner.Class("StepDependency")
	if err != nil {
		return nil, err
	}
	return &StepDependencyClassView{inner: bld}, nil
}

func (t *StepDependencyClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type StepVerificationClassView struct {
	inner baml.ClassBuilder
}

func (t *StepVerificationClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *StepVerificationClassView) PropertyMethod() (ClassPropertyView, error) {
	return t.inner.Property("method")
}

func (t *StepVerificationClassView) PropertyCommand() (ClassPropertyView, error) {
	return t.inner.Property("command")
}

func (t *StepVerificationClassView) PropertyExpected() (ClassPropertyView, error) {
	return t.inner.Property("expected")
}

func (t *StepVerificationClassView) PropertyDescription() (ClassPropertyView, error) {
	return t.inner.Property("description")
}

func (t *TypeBuilder) StepVerification() (*StepVerificationClassView, error) {
	bld, err := t.inner.Class("StepVerification")
	if err != nil {
		return nil, err
	}
	return &StepVerificationClassView{inner: bld}, nil
}

func (t *StepVerificationClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type TargetFileClassView struct {
	inner baml.ClassBuilder
}

func (t *TargetFileClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *TargetFileClassView) PropertyPath() (ClassPropertyView, error) {
	return t.inner.Property("path")
}

func (t *TargetFileClassView) PropertyAction() (ClassPropertyView, error) {
	return t.inner.Property("action")
}

func (t *TargetFileClassView) PropertyChange_type() (ClassPropertyView, error) {
	return t.inner.Property("change_type")
}

func (t *TargetFileClassView) PropertyReason() (ClassPropertyView, error) {
	return t.inner.Property("reason")
}

func (t *TypeBuilder) TargetFile() (*TargetFileClassView, error) {
	bld, err := t.inner.Class("TargetFile")
	if err != nil {
		return nil, err
	}
	return &TargetFileClassView{inner: bld}, nil
}

func (t *TargetFileClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type TestCaseClassView struct {
	inner baml.ClassBuilder
}

func (t *TestCaseClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *TestCaseClassView) PropertyName() (ClassPropertyView, error) {
	return t.inner.Property("name")
}

func (t *TestCaseClassView) PropertyDescription() (ClassPropertyView, error) {
	return t.inner.Property("description")
}

func (t *TestCaseClassView) PropertyTest_type() (ClassPropertyView, error) {
	return t.inner.Property("test_type")
}

func (t *TestCaseClassView) PropertyTarget_function() (ClassPropertyView, error) {
	return t.inner.Property("target_function")
}

func (t *TypeBuilder) TestCase() (*TestCaseClassView, error) {
	bld, err := t.inner.Class("TestCase")
	if err != nil {
		return nil, err
	}
	return &TestCaseClassView{inner: bld}, nil
}

func (t *TestCaseClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type TestCoverageAnalysisClassView struct {
	inner baml.ClassBuilder
}

func (t *TestCoverageAnalysisClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *TestCoverageAnalysisClassView) PropertyCovering_tests() (ClassPropertyView, error) {
	return t.inner.Property("covering_tests")
}

func (t *TestCoverageAnalysisClassView) PropertyCoverage_gaps() (ClassPropertyView, error) {
	return t.inner.Property("coverage_gaps")
}

func (t *TestCoverageAnalysisClassView) PropertyRecommendations() (ClassPropertyView, error) {
	return t.inner.Property("recommendations")
}

func (t *TypeBuilder) TestCoverageAnalysis() (*TestCoverageAnalysisClassView, error) {
	bld, err := t.inner.Class("TestCoverageAnalysis")
	if err != nil {
		return nil, err
	}
	return &TestCoverageAnalysisClassView{inner: bld}, nil
}

func (t *TestCoverageAnalysisClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type TestGenerationRequestClassView struct {
	inner baml.ClassBuilder
}

func (t *TestGenerationRequestClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *TestGenerationRequestClassView) PropertyTarget_file() (ClassPropertyView, error) {
	return t.inner.Property("target_file")
}

func (t *TestGenerationRequestClassView) PropertyTarget_content() (ClassPropertyView, error) {
	return t.inner.Property("target_content")
}

func (t *TestGenerationRequestClassView) PropertyExisting_tests() (ClassPropertyView, error) {
	return t.inner.Property("existing_tests")
}

func (t *TestGenerationRequestClassView) PropertyTest_framework() (ClassPropertyView, error) {
	return t.inner.Property("test_framework")
}

func (t *TestGenerationRequestClassView) PropertyCoverage_target() (ClassPropertyView, error) {
	return t.inner.Property("coverage_target")
}

func (t *TypeBuilder) TestGenerationRequest() (*TestGenerationRequestClassView, error) {
	bld, err := t.inner.Class("TestGenerationRequest")
	if err != nil {
		return nil, err
	}
	return &TestGenerationRequestClassView{inner: bld}, nil
}

func (t *TestGenerationRequestClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type TestGenerationResultClassView struct {
	inner baml.ClassBuilder
}

func (t *TestGenerationResultClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *TestGenerationResultClassView) PropertyTest_file_path() (ClassPropertyView, error) {
	return t.inner.Property("test_file_path")
}

func (t *TestGenerationResultClassView) PropertyTest_content() (ClassPropertyView, error) {
	return t.inner.Property("test_content")
}

func (t *TestGenerationResultClassView) PropertyTest_cases() (ClassPropertyView, error) {
	return t.inner.Property("test_cases")
}

func (t *TestGenerationResultClassView) PropertyCoverage_estimate() (ClassPropertyView, error) {
	return t.inner.Property("coverage_estimate")
}

func (t *TypeBuilder) TestGenerationResult() (*TestGenerationResultClassView, error) {
	bld, err := t.inner.Class("TestGenerationResult")
	if err != nil {
		return nil, err
	}
	return &TestGenerationResultClassView{inner: bld}, nil
}

func (t *TestGenerationResultClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type TestRecommendationClassView struct {
	inner baml.ClassBuilder
}

func (t *TestRecommendationClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *TestRecommendationClassView) PropertyTarget_file() (ClassPropertyView, error) {
	return t.inner.Property("target_file")
}

func (t *TestRecommendationClassView) PropertyTarget_symbol() (ClassPropertyView, error) {
	return t.inner.Property("target_symbol")
}

func (t *TestRecommendationClassView) PropertyTest_type() (ClassPropertyView, error) {
	return t.inner.Property("test_type")
}

func (t *TestRecommendationClassView) PropertyDescription() (ClassPropertyView, error) {
	return t.inner.Property("description")
}

func (t *TypeBuilder) TestRecommendation() (*TestRecommendationClassView, error) {
	bld, err := t.inner.Class("TestRecommendation")
	if err != nil {
		return nil, err
	}
	return &TestRecommendationClassView{inner: bld}, nil
}

func (t *TestRecommendationClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type TestReferenceClassView struct {
	inner baml.ClassBuilder
}

func (t *TestReferenceClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *TestReferenceClassView) PropertyFile_path() (ClassPropertyView, error) {
	return t.inner.Property("file_path")
}

func (t *TestReferenceClassView) PropertyTest_name() (ClassPropertyView, error) {
	return t.inner.Property("test_name")
}

func (t *TestReferenceClassView) PropertyCovers_files() (ClassPropertyView, error) {
	return t.inner.Property("covers_files")
}

func (t *TypeBuilder) TestReference() (*TestReferenceClassView, error) {
	bld, err := t.inner.Class("TestReference")
	if err != nil {
		return nil, err
	}
	return &TestReferenceClassView{inner: bld}, nil
}

func (t *TestReferenceClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}
