// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package type_builder

import baml "github.com/boundaryml/baml/engine/language_client_go/pkg"

type ChangeTypeEnumView struct {
	inner baml.EnumBuilder
}

func (t *ChangeTypeEnumView) ListValues() ([]EnumValueView, error) {
	result, err := t.inner.ListValues()
	if err != nil {
		return nil, err
	}
	builders := make([]EnumValueView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *ChangeTypeEnumView) ValueAdd() (EnumValueView, error) {
	return t.inner.Value("Add")
}

func (t *ChangeTypeEnumView) ValueModify() (EnumValueView, error) {
	return t.inner.Value("Modify")
}

func (t *ChangeTypeEnumView) ValueRemove() (EnumValueView, error) {
	return t.inner.Value("Remove")
}

func (t *ChangeTypeEnumView) ValueRefactor() (EnumValueView, error) {
	return t.inner.Value("Refactor")
}

func (t *TypeBuilder) ChangeType() (*ChangeTypeEnumView, error) {
	bld, err := t.inner.Enum("ChangeType")
	if err != nil {
		return nil, err
	}
	return &ChangeTypeEnumView{inner: bld}, nil
}

func (t *ChangeTypeEnumView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type CommitTypeEnumView struct {
	inner baml.EnumBuilder
}

func (t *CommitTypeEnumView) ListValues() ([]EnumValueView, error) {
	result, err := t.inner.ListValues()
	if err != nil {
		return nil, err
	}
	builders := make([]EnumValueView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *CommitTypeEnumView) ValueFeat() (EnumValueView, error) {
	return t.inner.Value("Feat")
}

func (t *CommitTypeEnumView) ValueFix() (EnumValueView, error) {
	return t.inner.Value("Fix")
}

func (t *CommitTypeEnumView) ValueRefactor() (EnumValueView, error) {
	return t.inner.Value("Refactor")
}

func (t *CommitTypeEnumView) ValueTest() (EnumValueView, error) {
	return t.inner.Value("Test")
}

func (t *CommitTypeEnumView) ValueDocs() (EnumValueView, error) {
	return t.inner.Value("Docs")
}

func (t *CommitTypeEnumView) ValueChore() (EnumValueView, error) {
	return t.inner.Value("Chore")
}

func (t *CommitTypeEnumView) ValueStyle() (EnumValueView, error) {
	return t.inner.Value("Style")
}

func (t *CommitTypeEnumView) ValuePerf() (EnumValueView, error) {
	return t.inner.Value("Perf")
}

func (t *TypeBuilder) CommitType() (*CommitTypeEnumView, error) {
	bld, err := t.inner.Enum("CommitType")
	if err != nil {
		return nil, err
	}
	return &CommitTypeEnumView{inner: bld}, nil
}

func (t *CommitTypeEnumView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type ComplexityLevelEnumView struct {
	inner baml.EnumBuilder
}

func (t *ComplexityLevelEnumView) ListValues() ([]EnumValueView, error) {
	result, err := t.inner.ListValues()
	if err != nil {
		return nil, err
	}
	builders := make([]EnumValueView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *ComplexityLevelEnumView) ValueTrivial() (EnumValueView, error) {
	return t.inner.Value("Trivial")
}

func (t *ComplexityLevelEnumView) ValueSimple() (EnumValueView, error) {
	return t.inner.Value("Simple")
}

func (t *ComplexityLevelEnumView) ValueModerate() (EnumValueView, error) {
	return t.inner.Value("Moderate")
}

func (t *ComplexityLevelEnumView) ValueComplex() (EnumValueView, error) {
	return t.inner.Value("Complex")
}

func (t *ComplexityLevelEnumView) ValueVeryComplex() (EnumValueView, error) {
	return t.inner.Value("VeryComplex")
}

func (t *TypeBuilder) ComplexityLevel() (*ComplexityLevelEnumView, error) {
	bld, err := t.inner.Enum("ComplexityLevel")
	if err != nil {
		return nil, err
	}
	return &ComplexityLevelEnumView{inner: bld}, nil
}

func (t *ComplexityLevelEnumView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type ComponentTypeEnumView struct {
	inner baml.EnumBuilder
}

func (t *ComponentTypeEnumView) ListValues() ([]EnumValueView, error) {
	result, err := t.inner.ListValues()
	if err != nil {
		return nil, err
	}
	builders := make([]EnumValueView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *ComponentTypeEnumView) ValueFile() (EnumValueView, error) {
	return t.inner.Value("File")
}

func (t *ComponentTypeEnumView) ValueFunction() (EnumValueView, error) {
	return t.inner.Value("Function")
}

func (t *ComponentTypeEnumView) ValueClass() (EnumValueView, error) {
	return t.inner.Value("Class")
}

func (t *ComponentTypeEnumView) ValueModule() (EnumValueView, error) {
	return t.inner.Value("Module")
}

func (t *ComponentTypeEnumView) ValuePackage() (EnumValueView, error) {
	return t.inner.Value("Package")
}

func (t *ComponentTypeEnumView) ValueConfig() (EnumValueView, error) {
	return t.inner.Value("Config")
}

func (t *ComponentTypeEnumView) ValueTest() (EnumValueView, error) {
	return t.inner.Value("Test")
}

func (t *TypeBuilder) ComponentType() (*ComponentTypeEnumView, error) {
	bld, err := t.inner.Enum("ComponentType")
	if err != nil {
		return nil, err
	}
	return &ComponentTypeEnumView{inner: bld}, nil
}

func (t *ComponentTypeEnumView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type DependencyKindEnumView struct {
	inner baml.EnumBuilder
}

func (t *DependencyKindEnumView) ListValues() ([]EnumValueView, error) {
	result, err := t.inner.ListValues()
	if err != nil {
		return nil, err
	}
	builders := make([]EnumValueView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *DependencyKindEnumView) ValueStrict() (EnumValueView, error) {
	return t.inner.Value("Strict")
}

func (t *DependencyKindEnumView) ValueSoft() (EnumValueView, error) {
	return t.inner.Value("Soft")
}

func (t *DependencyKindEnumView) ValueData() (EnumValueView, error) {
	return t.inner.Value("Data")
}

func (t *TypeBuilder) DependencyKind() (*DependencyKindEnumView, error) {
	bld, err := t.inner.Enum("DependencyKind")
	if err != nil {
		return nil, err
	}
	return &DependencyKindEnumView{inner: bld}, nil
}

func (t *DependencyKindEnumView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type EdgeTypeEnumView struct {
	inner baml.EnumBuilder
}

func (t *EdgeTypeEnumView) ListValues() ([]EnumValueView, error) {
	result, err := t.inner.ListValues()
	if err != nil {
		return nil, err
	}
	builders := make([]EnumValueView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *EdgeTypeEnumView) ValueImports() (EnumValueView, error) {
	return t.inner.Value("Imports")
}

func (t *EdgeTypeEnumView) ValueCalls() (EnumValueView, error) {
	return t.inner.Value("Calls")
}

func (t *EdgeTypeEnumView) ValueExtends() (EnumValueView, error) {
	return t.inner.Value("Extends")
}

func (t *EdgeTypeEnumView) ValueImplements() (EnumValueView, error) {
	return t.inner.Value("Implements")
}

func (t *EdgeTypeEnumView) ValueUses() (EnumValueView, error) {
	return t.inner.Value("Uses")
}

func (t *TypeBuilder) EdgeType() (*EdgeTypeEnumView, error) {
	bld, err := t.inner.Enum("EdgeType")
	if err != nil {
		return nil, err
	}
	return &EdgeTypeEnumView{inner: bld}, nil
}

func (t *EdgeTypeEnumView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type FeatureCategoryEnumView struct {
	inner baml.EnumBuilder
}

func (t *FeatureCategoryEnumView) ListValues() ([]EnumValueView, error) {
	result, err := t.inner.ListValues()
	if err != nil {
		return nil, err
	}
	builders := make([]EnumValueView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *FeatureCategoryEnumView) ValueNewFeature() (EnumValueView, error) {
	return t.inner.Value("NewFeature")
}

func (t *FeatureCategoryEnumView) ValueBugFix() (EnumValueView, error) {
	return t.inner.Value("BugFix")
}

func (t *FeatureCategoryEnumView) ValueRefactor() (EnumValueView, error) {
	return t.inner.Value("Refactor")
}

func (t *FeatureCategoryEnumView) ValueDocumentation() (EnumValueView, error) {
	return t.inner.Value("Documentation")
}

func (t *FeatureCategoryEnumView) ValueTest() (EnumValueView, error) {
	return t.inner.Value("Test")
}

func (t *FeatureCategoryEnumView) ValueDependency() (EnumValueView, error) {
	return t.inner.Value("Dependency")
}

func (t *TypeBuilder) FeatureCategory() (*FeatureCategoryEnumView, error) {
	bld, err := t.inner.Enum("FeatureCategory")
	if err != nil {
		return nil, err
	}
	return &FeatureCategoryEnumView{inner: bld}, nil
}

func (t *FeatureCategoryEnumView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type FileActionEnumView struct {
	inner baml.EnumBuilder
}

func (t *FileActionEnumView) ListValues() ([]EnumValueView, error) {
	result, err := t.inner.ListValues()
	if err != nil {
		return nil, err
	}
	builders := make([]EnumValueView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *FileActionEnumView) ValueCreate() (EnumValueView, error) {
	return t.inner.Value("Create")
}

func (t *FileActionEnumView) ValueModify() (EnumValueView, error) {
	return t.inner.Value("Modify")
}

func (t *FileActionEnumView) ValueDelete() (EnumValueView, error) {
	return t.inner.Value("Delete")
}

func (t *FileActionEnumView) ValueRename() (EnumValueView, error) {
	return t.inner.Value("Rename")
}

func (t *TypeBuilder) FileAction() (*FileActionEnumView, error) {
	bld, err := t.inner.Enum("FileAction")
	if err != nil {
		return nil, err
	}
	return &FileActionEnumView{inner: bld}, nil
}

func (t *FileActionEnumView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type FileChangeTypeEnumView struct {
	inner baml.EnumBuilder
}

func (t *FileChangeTypeEnumView) ListValues() ([]EnumValueView, error) {
	result, err := t.inner.ListValues()
	if err != nil {
		return nil, err
	}
	builders := make([]EnumValueView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *FileChangeTypeEnumView) ValueImplementation() (EnumValueView, error) {
	return t.inner.Value("Implementation")
}

func (t *FileChangeTypeEnumView) ValueTest() (EnumValueView, error) {
	return t.inner.Value("Test")
}

func (t *FileChangeTypeEnumView) ValueConfig() (EnumValueView, error) {
	return t.inner.Value("Config")
}

func (t *FileChangeTypeEnumView) ValueDocumentation() (EnumValueView, error) {
	return t.inner.Value("Documentation")
}

func (t *FileChangeTypeEnumView) ValueDependency() (EnumValueView, error) {
	return t.inner.Value("Dependency")
}

func (t *TypeBuilder) FileChangeType() (*FileChangeTypeEnumView, error) {
	bld, err := t.inner.Enum("FileChangeType")
	if err != nil {
		return nil, err
	}
	return &FileChangeTypeEnumView{inner: bld}, nil
}

func (t *FileChangeTypeEnumView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type ImpactTypeEnumView struct {
	inner baml.EnumBuilder
}

func (t *ImpactTypeEnumView) ListValues() ([]EnumValueView, error) {
	result, err := t.inner.ListValues()
	if err != nil {
		return nil, err
	}
	builders := make([]EnumValueView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *ImpactTypeEnumView) ValueCreate() (EnumValueView, error) {
	return t.inner.Value("Create")
}

func (t *ImpactTypeEnumView) ValueModify() (EnumValueView, error) {
	return t.inner.Value("Modify")
}

func (t *ImpactTypeEnumView) ValueDelete() (EnumValueView, error) {
	return t.inner.Value("Delete")
}

func (t *ImpactTypeEnumView) ValueRename() (EnumValueView, error) {
	return t.inner.Value("Rename")
}

func (t *ImpactTypeEnumView) ValueDependency() (EnumValueView, error) {
	return t.inner.Value("Dependency")
}

func (t *TypeBuilder) ImpactType() (*ImpactTypeEnumView, error) {
	bld, err := t.inner.Enum("ImpactType")
	if err != nil {
		return nil, err
	}
	return &ImpactTypeEnumView{inner: bld}, nil
}

func (t *ImpactTypeEnumView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type IterationStrategyEnumView struct {
	inner baml.EnumBuilder
}

func (t *IterationStrategyEnumView) ListValues() ([]EnumValueView, error) {
	result, err := t.inner.ListValues()
	if err != nil {
		return nil, err
	}
	builders := make([]EnumValueView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *IterationStrategyEnumView) ValueFix() (EnumValueView, error) {
	return t.inner.Value("Fix")
}

func (t *IterationStrategyEnumView) ValueRetry() (EnumValueView, error) {
	return t.inner.Value("Retry")
}

func (t *IterationStrategyEnumView) ValueReplan() (EnumValueView, error) {
	return t.inner.Value("Replan")
}

func (t *IterationStrategyEnumView) ValuePartial() (EnumValueView, error) {
	return t.inner.Value("Partial")
}

func (t *TypeBuilder) IterationStrategy() (*IterationStrategyEnumView, error) {
	bld, err := t.inner.Enum("IterationStrategy")
	if err != nil {
		return nil, err
	}
	return &IterationStrategyEnumView{inner: bld}, nil
}

func (t *IterationStrategyEnumView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type NodeTypeEnumView struct {
	inner baml.EnumBuilder
}

func (t *NodeTypeEnumView) ListValues() ([]EnumValueView, error) {
	result, err := t.inner.ListValues()
	if err != nil {
		return nil, err
	}
	builders := make([]EnumValueView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *NodeTypeEnumView) ValueFile() (EnumValueView, error) {
	return t.inner.Value("File")
}

func (t *NodeTypeEnumView) ValueFunction() (EnumValueView, error) {
	return t.inner.Value("Function")
}

func (t *NodeTypeEnumView) ValueClass() (EnumValueView, error) {
	return t.inner.Value("Class")
}

func (t *NodeTypeEnumView) ValueVariable() (EnumValueView, error) {
	return t.inner.Value("Variable")
}

func (t *NodeTypeEnumView) ValueType() (EnumValueView, error) {
	return t.inner.Value("Type")
}

func (t *TypeBuilder) NodeType() (*NodeTypeEnumView, error) {
	bld, err := t.inner.Enum("NodeType")
	if err != nil {
		return nil, err
	}
	return &NodeTypeEnumView{inner: bld}, nil
}

func (t *NodeTypeEnumView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type ReviewIssueSeverityEnumView struct {
	inner baml.EnumBuilder
}

func (t *ReviewIssueSeverityEnumView) ListValues() ([]EnumValueView, error) {
	result, err := t.inner.ListValues()
	if err != nil {
		return nil, err
	}
	builders := make([]EnumValueView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *ReviewIssueSeverityEnumView) ValueInfo() (EnumValueView, error) {
	return t.inner.Value("Info")
}

func (t *ReviewIssueSeverityEnumView) ValueLow() (EnumValueView, error) {
	return t.inner.Value("Low")
}

func (t *ReviewIssueSeverityEnumView) ValueMedium() (EnumValueView, error) {
	return t.inner.Value("Medium")
}

func (t *ReviewIssueSeverityEnumView) ValueHigh() (EnumValueView, error) {
	return t.inner.Value("High")
}

func (t *ReviewIssueSeverityEnumView) ValueCritical() (EnumValueView, error) {
	return t.inner.Value("Critical")
}

func (t *TypeBuilder) ReviewIssueSeverity() (*ReviewIssueSeverityEnumView, error) {
	bld, err := t.inner.Enum("ReviewIssueSeverity")
	if err != nil {
		return nil, err
	}
	return &ReviewIssueSeverityEnumView{inner: bld}, nil
}

func (t *ReviewIssueSeverityEnumView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type ReviewIssueTypeEnumView struct {
	inner baml.EnumBuilder
}

func (t *ReviewIssueTypeEnumView) ListValues() ([]EnumValueView, error) {
	result, err := t.inner.ListValues()
	if err != nil {
		return nil, err
	}
	builders := make([]EnumValueView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *ReviewIssueTypeEnumView) ValueBug() (EnumValueView, error) {
	return t.inner.Value("Bug")
}

func (t *ReviewIssueTypeEnumView) ValueSecurity() (EnumValueView, error) {
	return t.inner.Value("Security")
}

func (t *ReviewIssueTypeEnumView) ValuePerformance() (EnumValueView, error) {
	return t.inner.Value("Performance")
}

func (t *ReviewIssueTypeEnumView) ValueMaintainability() (EnumValueView, error) {
	return t.inner.Value("Maintainability")
}

func (t *ReviewIssueTypeEnumView) ValueStyle() (EnumValueView, error) {
	return t.inner.Value("Style")
}

func (t *ReviewIssueTypeEnumView) ValueDocumentation() (EnumValueView, error) {
	return t.inner.Value("Documentation")
}

func (t *ReviewIssueTypeEnumView) ValueComplexity() (EnumValueView, error) {
	return t.inner.Value("Complexity")
}

func (t *ReviewIssueTypeEnumView) ValueDeadCode() (EnumValueView, error) {
	return t.inner.Value("DeadCode")
}

func (t *ReviewIssueTypeEnumView) ValueDuplication() (EnumValueView, error) {
	return t.inner.Value("Duplication")
}

func (t *TypeBuilder) ReviewIssueType() (*ReviewIssueTypeEnumView, error) {
	bld, err := t.inner.Enum("ReviewIssueType")
	if err != nil {
		return nil, err
	}
	return &ReviewIssueTypeEnumView{inner: bld}, nil
}

func (t *ReviewIssueTypeEnumView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type ReviewRecommendationEnumView struct {
	inner baml.EnumBuilder
}

func (t *ReviewRecommendationEnumView) ListValues() ([]EnumValueView, error) {
	result, err := t.inner.ListValues()
	if err != nil {
		return nil, err
	}
	builders := make([]EnumValueView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *ReviewRecommendationEnumView) ValueApprove() (EnumValueView, error) {
	return t.inner.Value("Approve")
}

func (t *ReviewRecommendationEnumView) ValueApproveMinor() (EnumValueView, error) {
	return t.inner.Value("ApproveMinor")
}

func (t *ReviewRecommendationEnumView) ValueRequestChanges() (EnumValueView, error) {
	return t.inner.Value("RequestChanges")
}

func (t *ReviewRecommendationEnumView) ValueReject() (EnumValueView, error) {
	return t.inner.Value("Reject")
}

func (t *TypeBuilder) ReviewRecommendation() (*ReviewRecommendationEnumView, error) {
	bld, err := t.inner.Enum("ReviewRecommendation")
	if err != nil {
		return nil, err
	}
	return &ReviewRecommendationEnumView{inner: bld}, nil
}

func (t *ReviewRecommendationEnumView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type RiskLevelEnumView struct {
	inner baml.EnumBuilder
}

func (t *RiskLevelEnumView) ListValues() ([]EnumValueView, error) {
	result, err := t.inner.ListValues()
	if err != nil {
		return nil, err
	}
	builders := make([]EnumValueView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *RiskLevelEnumView) ValueLow() (EnumValueView, error) {
	return t.inner.Value("Low")
}

func (t *RiskLevelEnumView) ValueMedium() (EnumValueView, error) {
	return t.inner.Value("Medium")
}

func (t *RiskLevelEnumView) ValueHigh() (EnumValueView, error) {
	return t.inner.Value("High")
}

func (t *RiskLevelEnumView) ValueCritical() (EnumValueView, error) {
	return t.inner.Value("Critical")
}

func (t *TypeBuilder) RiskLevel() (*RiskLevelEnumView, error) {
	bld, err := t.inner.Enum("RiskLevel")
	if err != nil {
		return nil, err
	}
	return &RiskLevelEnumView{inner: bld}, nil
}

func (t *RiskLevelEnumView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type TestTypeEnumView struct {
	inner baml.EnumBuilder
}

func (t *TestTypeEnumView) ListValues() ([]EnumValueView, error) {
	result, err := t.inner.ListValues()
	if err != nil {
		return nil, err
	}
	builders := make([]EnumValueView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *TestTypeEnumView) ValueUnit() (EnumValueView, error) {
	return t.inner.Value("Unit")
}

func (t *TestTypeEnumView) ValueIntegration() (EnumValueView, error) {
	return t.inner.Value("Integration")
}

func (t *TestTypeEnumView) ValueE2E() (EnumValueView, error) {
	return t.inner.Value("E2E")
}

func (t *TestTypeEnumView) ValueSnapshot() (EnumValueView, error) {
	return t.inner.Value("Snapshot")
}

func (t *TestTypeEnumView) ValueProperty() (EnumValueView, error) {
	return t.inner.Value("Property")
}

func (t *TypeBuilder) TestType() (*TestTypeEnumView, error) {
	bld, err := t.inner.Enum("TestType")
	if err != nil {
		return nil, err
	}
	return &TestTypeEnumView{inner: bld}, nil
}

func (t *TestTypeEnumView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type VerificationMethodEnumView struct {
	inner baml.EnumBuilder
}

func (t *VerificationMethodEnumView) ListValues() ([]EnumValueView, error) {
	result, err := t.inner.ListValues()
	if err != nil {
		return nil, err
	}
	builders := make([]EnumValueView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *VerificationMethodEnumView) ValueSyntaxCheck() (EnumValueView, error) {
	return t.inner.Value("SyntaxCheck")
}

func (t *VerificationMethodEnumView) ValueBuild() (EnumValueView, error) {
	return t.inner.Value("Build")
}

func (t *VerificationMethodEnumView) ValueTest() (EnumValueView, error) {
	return t.inner.Value("Test")
}

func (t *VerificationMethodEnumView) ValueLint() (EnumValueView, error) {
	return t.inner.Value("Lint")
}

func (t *VerificationMethodEnumView) ValueManual() (EnumValueView, error) {
	return t.inner.Value("Manual")
}

func (t *TypeBuilder) VerificationMethod() (*VerificationMethodEnumView, error) {
	bld, err := t.inner.Enum("VerificationMethod")
	if err != nil {
		return nil, err
	}
	return &VerificationMethodEnumView{inner: bld}, nil
}

func (t *VerificationMethodEnumView) Type() (baml.Type, error) {
	return t.inner.Type()
}
