// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"context"
	"fmt"

	"github.com/antinvestor/builder/baml_client/baml_client/stream_types"
	"github.com/antinvestor/builder/baml_client/baml_client/types"
	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
)

type stream struct{}

var Stream = &stream{}

type StreamValue[TStream any, TFinal any] struct {
	IsError   bool
	Error     error
	IsFinal   bool
	as_final  *TFinal
	as_stream *TStream
}

func (s *StreamValue[TStream, TFinal]) Final() *TFinal {
	return s.as_final
}

func (s *StreamValue[TStream, TFinal]) Stream() *TStream {
	return s.as_stream
}

// / Streaming version of AnalyzeImpact
func (*stream) AnalyzeImpact(ctx context.Context, normalized_spec types.NormalizedSpecification, file_contents map[string]string, project_structure string, opts ...CallOptionFunc) (<-chan StreamValue[stream_types.ImpactAnalysisResult, types.ImpactAnalysisResult], error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"normalized_spec": normalized_spec, "file_contents": file_contents, "project_structure": project_structure},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: AnalyzeImpact: %w", err)
		panic(wrapped_err)
	}

	internal_channel, err := bamlRuntime.CallFunctionStream(ctx, "AnalyzeImpact", encoded, callOpts.onTick)
	if err != nil {
		return nil, err
	}

	channel := make(chan StreamValue[stream_types.ImpactAnalysisResult, types.ImpactAnalysisResult])
	go func() {
		for result := range internal_channel {
			if result.Error != nil {
				channel <- StreamValue[stream_types.ImpactAnalysisResult, types.ImpactAnalysisResult]{
					IsError: true,
					Error:   result.Error,
				}
				close(channel)
				return
			}
			if result.HasData {
				data := (result.Data).(types.ImpactAnalysisResult)
				channel <- StreamValue[stream_types.ImpactAnalysisResult, types.ImpactAnalysisResult]{
					IsFinal:  true,
					as_final: &data,
				}
			} else {
				data := (result.StreamData).(stream_types.ImpactAnalysisResult)
				channel <- StreamValue[stream_types.ImpactAnalysisResult, types.ImpactAnalysisResult]{
					IsFinal:   false,
					as_stream: &data,
				}
			}
		}

		// when internal_channel is closed, close the output too
		close(channel)
	}()
	return channel, nil
}

// / Streaming version of GenerateCode
func (*stream) GenerateCode(ctx context.Context, request types.CodeGenerationRequest, opts ...CallOptionFunc) (<-chan StreamValue[stream_types.CodeGenerationResult, types.CodeGenerationResult], error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"request": request},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: GenerateCode: %w", err)
		panic(wrapped_err)
	}

	internal_channel, err := bamlRuntime.CallFunctionStream(ctx, "GenerateCode", encoded, callOpts.onTick)
	if err != nil {
		return nil, err
	}

	channel := make(chan StreamValue[stream_types.CodeGenerationResult, types.CodeGenerationResult])
	go func() {
		for result := range internal_channel {
			if result.Error != nil {
				channel <- StreamValue[stream_types.CodeGenerationResult, types.CodeGenerationResult]{
					IsError: true,
					Error:   result.Error,
				}
				close(channel)
				return
			}
			if result.HasData {
				data := (result.Data).(types.CodeGenerationResult)
				channel <- StreamValue[stream_types.CodeGenerationResult, types.CodeGenerationResult]{
					IsFinal:  true,
					as_final: &data,
				}
			} else {
				data := (result.StreamData).(stream_types.CodeGenerationResult)
				channel <- StreamValue[stream_types.CodeGenerationResult, types.CodeGenerationResult]{
					IsFinal:   false,
					as_stream: &data,
				}
			}
		}

		// when internal_channel is closed, close the output too
		close(channel)
	}()
	return channel, nil
}

// / Streaming version of GenerateCommitMessage
func (*stream) GenerateCommitMessage(ctx context.Context, request types.CommitMessageRequest, opts ...CallOptionFunc) (<-chan StreamValue[stream_types.CommitMessage, types.CommitMessage], error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"request": request},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: GenerateCommitMessage: %w", err)
		panic(wrapped_err)
	}

	internal_channel, err := bamlRuntime.CallFunctionStream(ctx, "GenerateCommitMessage", encoded, callOpts.onTick)
	if err != nil {
		return nil, err
	}

	channel := make(chan StreamValue[stream_types.CommitMessage, types.CommitMessage])
	go func() {
		for result := range internal_channel {
			if result.Error != nil {
				channel <- StreamValue[stream_types.CommitMessage, types.CommitMessage]{
					IsError: true,
					Error:   result.Error,
				}
				close(channel)
				return
			}
			if result.HasData {
				data := (result.Data).(types.CommitMessage)
				channel <- StreamValue[stream_types.CommitMessage, types.CommitMessage]{
					IsFinal:  true,
					as_final: &data,
				}
			} else {
				data := (result.StreamData).(stream_types.CommitMessage)
				channel <- StreamValue[stream_types.CommitMessage, types.CommitMessage]{
					IsFinal:   false,
					as_stream: &data,
				}
			}
		}

		// when internal_channel is closed, close the output too
		close(channel)
	}()
	return channel, nil
}

// / Streaming version of GeneratePlan
func (*stream) GeneratePlan(ctx context.Context, normalized_spec types.NormalizedSpecification, impact_analysis types.ImpactAnalysisResult, file_contents map[string]string, project_info string, opts ...CallOptionFunc) (<-chan StreamValue[stream_types.ImplementationPlan, types.ImplementationPlan], error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"normalized_spec": normalized_spec, "impact_analysis": impact_analysis, "file_contents": file_contents, "project_info": project_info},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: GeneratePlan: %w", err)
		panic(wrapped_err)
	}

	internal_channel, err := bamlRuntime.CallFunctionStream(ctx, "GeneratePlan", encoded, callOpts.onTick)
	if err != nil {
		return nil, err
	}

	channel := make(chan StreamValue[stream_types.ImplementationPlan, types.ImplementationPlan])
	go func() {
		for result := range internal_channel {
			if result.Error != nil {
				channel <- StreamValue[stream_types.ImplementationPlan, types.ImplementationPlan]{
					IsError: true,
					Error:   result.Error,
				}
				close(channel)
				return
			}
			if result.HasData {
				data := (result.Data).(types.ImplementationPlan)
				channel <- StreamValue[stream_types.ImplementationPlan, types.ImplementationPlan]{
					IsFinal:  true,
					as_final: &data,
				}
			} else {
				data := (result.StreamData).(stream_types.ImplementationPlan)
				channel <- StreamValue[stream_types.ImplementationPlan, types.ImplementationPlan]{
					IsFinal:   false,
					as_stream: &data,
				}
			}
		}

		// when internal_channel is closed, close the output too
		close(channel)
	}()
	return channel, nil
}

// / Streaming version of GenerateTests
func (*stream) GenerateTests(ctx context.Context, request types.TestGenerationRequest, opts ...CallOptionFunc) (<-chan StreamValue[stream_types.TestGenerationResult, types.TestGenerationResult], error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"request": request},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: GenerateTests: %w", err)
		panic(wrapped_err)
	}

	internal_channel, err := bamlRuntime.CallFunctionStream(ctx, "GenerateTests", encoded, callOpts.onTick)
	if err != nil {
		return nil, err
	}

	channel := make(chan StreamValue[stream_types.TestGenerationResult, types.TestGenerationResult])
	go func() {
		for result := range internal_channel {
			if result.Error != nil {
				channel <- StreamValue[stream_types.TestGenerationResult, types.TestGenerationResult]{
					IsError: true,
					Error:   result.Error,
				}
				close(channel)
				return
			}
			if result.HasData {
				data := (result.Data).(types.TestGenerationResult)
				channel <- StreamValue[stream_types.TestGenerationResult, types.TestGenerationResult]{
					IsFinal:  true,
					as_final: &data,
				}
			} else {
				data := (result.StreamData).(stream_types.TestGenerationResult)
				channel <- StreamValue[stream_types.TestGenerationResult, types.TestGenerationResult]{
					IsFinal:   false,
					as_stream: &data,
				}
			}
		}

		// when internal_channel is closed, close the output too
		close(channel)
	}()
	return channel, nil
}

// / Streaming version of NormalizeSpecification
func (*stream) NormalizeSpecification(ctx context.Context, spec types.FeatureSpecification, codebase_context string, language string, opts ...CallOptionFunc) (<-chan StreamValue[stream_types.NormalizedSpecification, types.NormalizedSpecification], error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"spec": spec, "codebase_context": codebase_context, "language": language},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: NormalizeSpecification: %w", err)
		panic(wrapped_err)
	}

	internal_channel, err := bamlRuntime.CallFunctionStream(ctx, "NormalizeSpecification", encoded, callOpts.onTick)
	if err != nil {
		return nil, err
	}

	channel := make(chan StreamValue[stream_types.NormalizedSpecification, types.NormalizedSpecification])
	go func() {
		for result := range internal_channel {
			if result.Error != nil {
				channel <- StreamValue[stream_types.NormalizedSpecification, types.NormalizedSpecification]{
					IsError: true,
					Error:   result.Error,
				}
				close(channel)
				return
			}
			if result.HasData {
				data := (result.Data).(types.NormalizedSpecification)
				channel <- StreamValue[stream_types.NormalizedSpecification, types.NormalizedSpecification]{
					IsFinal:  true,
					as_final: &data,
				}
			} else {
				data := (result.StreamData).(stream_types.NormalizedSpecification)
				channel <- StreamValue[stream_types.NormalizedSpecification, types.NormalizedSpecification]{
					IsFinal:   false,
					as_stream: &data,
				}
			}
		}

		// when internal_channel is closed, close the output too
		close(channel)
	}()
	return channel, nil
}

// / Streaming version of PlanIteration
func (*stream) PlanIteration(ctx context.Context, request types.IterationRequest, opts ...CallOptionFunc) (<-chan StreamValue[stream_types.IterationPlan, types.IterationPlan], error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"request": request},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: PlanIteration: %w", err)
		panic(wrapped_err)
	}

	internal_channel, err := bamlRuntime.CallFunctionStream(ctx, "PlanIteration", encoded, callOpts.onTick)
	if err != nil {
		return nil, err
	}

	channel := make(chan StreamValue[stream_types.IterationPlan, types.IterationPlan])
	go func() {
		for result := range internal_channel {
			if result.Error != nil {
				channel <- StreamValue[stream_types.IterationPlan, types.IterationPlan]{
					IsError: true,
					Error:   result.Error,
				}
				close(channel)
				return
			}
			if result.HasData {
				data := (result.Data).(types.IterationPlan)
				channel <- StreamValue[stream_types.IterationPlan, types.IterationPlan]{
					IsFinal:  true,
					as_final: &data,
				}
			} else {
				data := (result.StreamData).(stream_types.IterationPlan)
				channel <- StreamValue[stream_types.IterationPlan, types.IterationPlan]{
					IsFinal:   false,
					as_stream: &data,
				}
			}
		}

		// when internal_channel is closed, close the output too
		close(channel)
	}()
	return channel, nil
}

// / Streaming version of ReviewCode
func (*stream) ReviewCode(ctx context.Context, request types.ReviewRequest, opts ...CallOptionFunc) (<-chan StreamValue[stream_types.ReviewAssessment, types.ReviewAssessment], error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"request": request},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: ReviewCode: %w", err)
		panic(wrapped_err)
	}

	internal_channel, err := bamlRuntime.CallFunctionStream(ctx, "ReviewCode", encoded, callOpts.onTick)
	if err != nil {
		return nil, err
	}

	channel := make(chan StreamValue[stream_types.ReviewAssessment, types.ReviewAssessment])
	go func() {
		for result := range internal_channel {
			if result.Error != nil {
				channel <- StreamValue[stream_types.ReviewAssessment, types.ReviewAssessment]{
					IsError: true,
					Error:   result.Error,
				}
				close(channel)
				return
			}
			if result.HasData {
				data := (result.Data).(types.ReviewAssessment)
				channel <- StreamValue[stream_types.ReviewAssessment, types.ReviewAssessment]{
					IsFinal:  true,
					as_final: &data,
				}
			} else {
				data := (result.StreamData).(stream_types.ReviewAssessment)
				channel <- StreamValue[stream_types.ReviewAssessment, types.ReviewAssessment]{
					IsFinal:   false,
					as_stream: &data,
				}
			}
		}

		// when internal_channel is closed, close the output too
		close(channel)
	}()
	return channel, nil
}
