// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"context"
	"fmt"

	"github.com/antinvestor/builder/baml_client/baml_client/types"
	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
)

func AnalyzeImpact(ctx context.Context, normalized_spec types.NormalizedSpecification, file_contents map[string]string, project_structure string, opts ...CallOptionFunc) (types.ImpactAnalysisResult, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"normalized_spec": normalized_spec, "file_contents": file_contents, "project_structure": project_structure},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "AnalyzeImpact", encoded, callOpts.onTick)
		if err != nil {
			return types.ImpactAnalysisResult{}, err
		}

		if result.Error != nil {
			return types.ImpactAnalysisResult{}, result.Error
		}

		casted := (result.Data).(types.ImpactAnalysisResult)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "AnalyzeImpact", encoded, callOpts.onTick)
		if err != nil {
			return types.ImpactAnalysisResult{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.ImpactAnalysisResult{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.ImpactAnalysisResult), nil
			}
		}

		return types.ImpactAnalysisResult{}, fmt.Errorf("No data returned from stream")
	}
}

func GenerateCode(ctx context.Context, request types.CodeGenerationRequest, opts ...CallOptionFunc) (types.CodeGenerationResult, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"request": request},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "GenerateCode", encoded, callOpts.onTick)
		if err != nil {
			return types.CodeGenerationResult{}, err
		}

		if result.Error != nil {
			return types.CodeGenerationResult{}, result.Error
		}

		casted := (result.Data).(types.CodeGenerationResult)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "GenerateCode", encoded, callOpts.onTick)
		if err != nil {
			return types.CodeGenerationResult{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.CodeGenerationResult{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.CodeGenerationResult), nil
			}
		}

		return types.CodeGenerationResult{}, fmt.Errorf("No data returned from stream")
	}
}

func GenerateCommitMessage(ctx context.Context, request types.CommitMessageRequest, opts ...CallOptionFunc) (types.CommitMessage, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"request": request},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "GenerateCommitMessage", encoded, callOpts.onTick)
		if err != nil {
			return types.CommitMessage{}, err
		}

		if result.Error != nil {
			return types.CommitMessage{}, result.Error
		}

		casted := (result.Data).(types.CommitMessage)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "GenerateCommitMessage", encoded, callOpts.onTick)
		if err != nil {
			return types.CommitMessage{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.CommitMessage{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.CommitMessage), nil
			}
		}

		return types.CommitMessage{}, fmt.Errorf("No data returned from stream")
	}
}

func GeneratePlan(ctx context.Context, normalized_spec types.NormalizedSpecification, impact_analysis types.ImpactAnalysisResult, file_contents map[string]string, project_info string, opts ...CallOptionFunc) (types.ImplementationPlan, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"normalized_spec": normalized_spec, "impact_analysis": impact_analysis, "file_contents": file_contents, "project_info": project_info},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "GeneratePlan", encoded, callOpts.onTick)
		if err != nil {
			return types.ImplementationPlan{}, err
		}

		if result.Error != nil {
			return types.ImplementationPlan{}, result.Error
		}

		casted := (result.Data).(types.ImplementationPlan)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "GeneratePlan", encoded, callOpts.onTick)
		if err != nil {
			return types.ImplementationPlan{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.ImplementationPlan{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.ImplementationPlan), nil
			}
		}

		return types.ImplementationPlan{}, fmt.Errorf("No data returned from stream")
	}
}

func GenerateTests(ctx context.Context, request types.TestGenerationRequest, opts ...CallOptionFunc) (types.TestGenerationResult, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"request": request},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "GenerateTests", encoded, callOpts.onTick)
		if err != nil {
			return types.TestGenerationResult{}, err
		}

		if result.Error != nil {
			return types.TestGenerationResult{}, result.Error
		}

		casted := (result.Data).(types.TestGenerationResult)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "GenerateTests", encoded, callOpts.onTick)
		if err != nil {
			return types.TestGenerationResult{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.TestGenerationResult{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.TestGenerationResult), nil
			}
		}

		return types.TestGenerationResult{}, fmt.Errorf("No data returned from stream")
	}
}

func NormalizeSpecification(ctx context.Context, spec types.FeatureSpecification, codebase_context string, language string, opts ...CallOptionFunc) (types.NormalizedSpecification, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"spec": spec, "codebase_context": codebase_context, "language": language},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "NormalizeSpecification", encoded, callOpts.onTick)
		if err != nil {
			return types.NormalizedSpecification{}, err
		}

		if result.Error != nil {
			return types.NormalizedSpecification{}, result.Error
		}

		casted := (result.Data).(types.NormalizedSpecification)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "NormalizeSpecification", encoded, callOpts.onTick)
		if err != nil {
			return types.NormalizedSpecification{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.NormalizedSpecification{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.NormalizedSpecification), nil
			}
		}

		return types.NormalizedSpecification{}, fmt.Errorf("No data returned from stream")
	}
}

func PlanIteration(ctx context.Context, request types.IterationRequest, opts ...CallOptionFunc) (types.IterationPlan, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"request": request},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "PlanIteration", encoded, callOpts.onTick)
		if err != nil {
			return types.IterationPlan{}, err
		}

		if result.Error != nil {
			return types.IterationPlan{}, result.Error
		}

		casted := (result.Data).(types.IterationPlan)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "PlanIteration", encoded, callOpts.onTick)
		if err != nil {
			return types.IterationPlan{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.IterationPlan{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.IterationPlan), nil
			}
		}

		return types.IterationPlan{}, fmt.Errorf("No data returned from stream")
	}
}

func ReviewCode(ctx context.Context, request types.ReviewRequest, opts ...CallOptionFunc) (types.ReviewAssessment, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"request": request},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "ReviewCode", encoded, callOpts.onTick)
		if err != nil {
			return types.ReviewAssessment{}, err
		}

		if result.Error != nil {
			return types.ReviewAssessment{}, result.Error
		}

		casted := (result.Data).(types.ReviewAssessment)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "ReviewCode", encoded, callOpts.onTick)
		if err != nil {
			return types.ReviewAssessment{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.ReviewAssessment{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.ReviewAssessment), nil
			}
		}

		return types.ReviewAssessment{}, fmt.Errorf("No data returned from stream")
	}
}
